### ISSUE TITLE
Type in @gqlField requires string literal - TS notation is not allowed

### ISSUE THREAD

**Issue by rvlasveld** [lolopinto/ent#1285]
When defining a graphql Field, the `{type: ...}` annotation seems to require a string literal. In comparison, `@gqlMutation` allows to use the Typescript types directly. 

Example code that is _not_ working, in e.g. `account.ts` (which has many `Transaction` objects):

```typescript
@gqlField({type: [Transaction]})
recentTransactions(): Transaction[] {
  return [];
}
```

Fails with:

```
npm run codegen

> fortunas-server@0.0.1 codegen
> tsent codegen

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
checking for custom graphql definitions...
Error: Error: Function isn't a valid type for accessor/function/property loading /Users/roemer/projects/fortunas-server/src/ent/index.ts
    at /Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:213:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requireFiles (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:200:5)
    at async captureCustom (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:165:9)
    at async Promise.all (index 1)
    at async main (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:278:38)
```

and 

```typescript
@gqlField({type: Transaction, nullable: true})
recentTransactions(): Transaction | null {
  return null;
}
```

fails with:

```
npm run codegen

> fortunas-server@0.0.1 codegen
> tsent codegen

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
checking for custom graphql definitions...
Error: Error: Cannot read properties of undefined (reading 'push') loading /Users/roemer/projects/fortunas-server/src/ent/index.ts
    at /Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:213:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requireFiles (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:200:5)
    at async captureCustom (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:165:9)
    at async Promise.all (index 1)
    at async main (/Users/roemer/projects/fortunas-server/node_modules/@snowtop/ent/scripts/custom_graphql.js:278:38)
```

Currently, it seems that only using a string literal for the type works, as such:

```typescript
@gqlField({type: "Transaction", nullable: true})
recentTransactions(): Transaction | null {
  return null;
}
```

**Comment by lolopinto** [comment]
I believe this is related to the circular dependency because of how ents are intertwined. I don't have a great solution to fix it yet.

a little bit more on how the circular dependencies are structured: https://github.com/lolopinto/ent/issues/1228

using https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

same thing in the examples :(
https://github.com/lolopinto/ent/blob/de358a1147dd98a9a92b0a84aefee8b958a355ea/examples/simple/src/ent/user.ts#L173-L199

**Comment by lolopinto** [comment]
oh yah, this is one thing I did document https://ent.dev/docs/custom-graphql/gql-field#string

**Comment by rvlasveld** [comment]
Ah that's right! Oh well... not a super big issue :)
