### ISSUE TITLE
gqlObjectType cannot be defined outside resolvers

### ISSUE THREAD

**Issue by rvlasveld** [lolopinto/ent#1286]
My goal is to add a `@gqlField` to an ent, for which the return type is a composed type / class. I'm trying to use `@gqlObjectType` to create a graphql definition for that type, but it seems that it's not picked up. 

Example: 
- Ent `Account` has many transactions. 
- We want to add an accessor `historicBalances`. It returns a list of `HistoricBalance` objects, which compose of the `date` and `balance`. 

```typescript
@gqlObjectType({name: "HistoricBalance"})
export class HistoricBalance {
  date: Date;
  balance: number;
}

export class Account extends AccountBase {
  @gqlField({name: "historicBalances", type: "[HistoricBalance]"})
  async historicBalances(): Promise<HistoricBalance[]> {
    return [];
  }
}
```

The `codegen` steps completes, but when running the server, it fails with this:

```
/Users/roemer/projects/fortunas-server/node_modules/graphql/jsutils/devAssert.js:12
    throw new Error(message);
    ^

Error: Expected undefined to be a GraphQL nullable type.
    at devAssert (/Users/roemer/projects/fortunas-server/node_modules/graphql/jsutils/devAssert.js:12:11)
    at new GraphQLNonNull (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/definition.js:395:32)
    at fields (/Users/roemer/projects/fortunas-server/dist/graphql/generated/resolvers/account_type.js:74:74)
    at resolveObjMapThunk (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/definition.js:504:40)
    at defineFieldMap (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/definition.js:766:20)
    at GraphQLObjectType._fields (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/definition.js:691:26)
    at GraphQLObjectType.getFields (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/definition.js:710:27)
    at collectReferencedTypes (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/schema.js:387:51)
    at new GraphQLSchema (/Users/roemer/projects/fortunas-server/node_modules/graphql/type/schema.js:174:9)
    at Object.<anonymous> (/Users/roemer/projects/fortunas-server/dist/graphql/generated/schema.js:24:19)
```

It seems that the `@gqlObjectType` isn't part of the generated code. Looking at the examples, it's so far only used in mutations and resolvers. In this case, a resolver isn't the right location, since this should be a field on an existing object.

**Comment by lolopinto** [comment]
will take a look at this and the other ones later today or tomorrow. 

Thanks for diving into custom accessors and finding issues~

**Comment by lolopinto** [comment]
intentionally didn't support it but should probably have thrown.

Now support it in `src/ent/*.ts`

**Comment by lolopinto** [comment]
fixed in latest
