### ISSUE TITLE
need a "refactor" mode where typescript errors are allowed 

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#253]
below: error in action
```2021/03/19 13:51:41 wrote to file  src/graphql/resolvers/index.ts

/usr/local/lib/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/ent/guest/actions/create_guest_action.ts:26:31 - error TS2339: Property 'emailAddress' does not exist on type 'GuestCreateInput'.

26           emailAddress: input.emailAddress,
                                 ~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
Error: error writing schema file: exit status 1
Usage:
  tsent codegen [flags]

Flags:
  -h, --help          help for codegen
  -s, --step string   limit to only run a particular step e.g. db, graphql, codegen

error writing schema file: exit status 1
```

error in custom graphql file
```
2021/03/19 13:53:15 wrote to file  src/graphql/resolvers/index.ts

/usr/local/lib/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/graphql/mutations/import_guests.ts:84:9 - error TS2345: Argument of type '{ eventID: string | number; guestGroupID: GuestGroupBuilder; firstName: any; lastName: any; emailAddress: any; }' is not assignable to parameter of type 'GuestCreateInput'.
  Object literal may only specify known properties, and 'firstName' does not exist in type 'GuestCreateInput'.

84         firstName: row.firstName,
           ~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
Error: error writing schema file: exit status 1
```

or maybe refactor mode is default?

**Comment by lolopinto** [comment]
https://github.com/lolopinto/ent/issues/440 has better information
