### ISSUE TITLE
typescript is needed in production

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#277]
from render:

#9 [5/6] RUN npm run compile
Apr 22 12:10:49 PM  #9 1.300
Apr 22 12:10:49 PM  #9 1.300 > ent-rsvp@1.0.0 compile /app
Apr 22 12:10:49 PM  #9 1.300 > rm -rf dist && ./node_modules/.bin/ent-custom-compiler
Apr 22 12:10:49 PM  #9 1.300
Apr 22 12:10:50 PM  #9 1.779 couldn't resolve everything [ 'node:fs', 'node:events', 'node:net', 'node:stream' ] []
Apr 22 12:10:50 PM  #9 1.797 /app/node_modules/typescript/lib/typescript.js:2251
Apr 22 12:10:50 PM  #9 1.797             throw e;
Apr 22 12:10:50 PM  #9 1.797             ^
Apr 22 12:10:50 PM  #9 1.797
Apr 22 12:10:50 PM  #9 1.797 Error: Debug Failure. False expression.
Apr 22 12:10:50 PM  #9 1.797     at resolveModuleNamesReusingOldState (/app/node_modules/typescript/lib/typescript.js:100456:22)
Apr 22 12:10:50 PM  #9 1.797     at processImportedModules (/app/node_modules/typescript/lib/typescript.js:101847:35)
Apr 22 12:10:50 PM  #9 1.797     at findSourceFile (/app/node_modules/typescript/lib/typescript.js:101590:17)
Apr 22 12:10:50 PM  #9 1.797     at /app/node_modules/typescript/lib/typescript.js:101419:85
Apr 22 12:10:50 PM  #9 1.797     at getSourceFileFromReferenceWorker (/app/node_modules/typescript/lib/typescript.js:101386:34)
Apr 22 12:10:50 PM  #9 1.797     at processSourceFile (/app/node_modules/typescript/lib/typescript.js:101419:13)
Apr 22 12:10:50 PM  #9 1.797     at /app/node_modules/typescript/lib/typescript.js:101729:17
Apr 22 12:10:50 PM  #9 1.797     at Object.forEach (/app/node_modules/typescript/lib/typescript.js:317:30)
Apr 22 12:10:50 PM  #9 1.797     at processReferencedFiles (/app/node_modules/typescript/lib/typescript.js:101727:16)
Apr 22 12:10:50 PM  #9 1.797     at findSourceFile (/app/node_modules/typescript/lib/typescript.js:101583:21)
Apr 22 12:10:50 PM  #9 1.809 npm ERR! code ELIFECYCLE
Apr 22 12:10:50 PM  #9 1.810 npm ERR! errno 1
Apr 22 12:10:50 PM  #9 1.815 npm ERR! ent-rsvp@1.0.0 compile: `rm -rf dist && ./node_modules/.bin/ent-custom-compiler`
Apr 22 12:10:50 PM  #9 1.815 npm ERR! Exit status 1
Apr 22 12:10:50 PM  #9 1.816 npm ERR!
Apr 22 12:10:50 PM  #9 1.816 npm ERR! Failed at the ent-rsvp@1.0.0 compile script.
Apr 22 12:10:50 PM  #9 1.816 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Apr 22 12:10:50 PM  #9 1.851
Apr 22 12:10:50 PM  #9 1.851 npm ERR! A complete log of this run can be found in:
Apr 22 12:10:50 PM  #9 1.852 npm ERR!     /root/.npm/_logs/2021-04-22T19_10_50_295Z-debug.log
Apr 22 12:10:50 PM  #9 ERROR: executor failed running [/bin/sh -c npm run compile]: buildkit-runc did not terminate successfully

**Comment by lolopinto** [comment]
it's in package.json and multiple recent deploys have worked

https://github.com/lolopinto/ent/blob/main/ts/package.json#L27
