### ISSUE TITLE
trying to add a new non-null field when there's data in the table causes an error

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#35]
command run was `tsent codegen`

output is below: 
```ola@Olas-personal-MBP simple % tsent codegen
2020/03/18 10:50:58 wrote to file  src/schema/schema.py
Generating /Users/ola/code/ent/ts/examples/simple/src/schema/versions/2d3f00438240_2020318175059_add_column_email_address_to_table_users_.py ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "email_address" contains null values


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ola/code/ent/python/auto_schema/gen_db_schema.py", line 37, in <module>
    r.run()
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/runner.py", line 156, in run
    self._apply_changes(diff)
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/runner.py", line 168, in _apply_changes
    self.upgrade()
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/runner.py", line 222, in upgrade
    self.cmd.upgrade()
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/command.py", line 40, in upgrade
    command.upgrade(self.alembic_cfg, revision)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/env.py", line 137, in <module>
    run_migrations_online()
  File "/Users/ola/code/ent/python/auto_schema/auto_schema/env.py", line 130, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/Users/ola/code/ent/ts/examples/simple/src/schema/versions/2d3f00438240_2020318175059_add_column_email_address_to_table_users_.py", line 24, in upgrade
    op.add_column('users', sa.Column('email_address', sa.Text(), nullable=False))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/ops.py", line 1904, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 230, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "email_address" contains null values

[SQL: ALTER TABLE users ADD COLUMN email_address TEXT NOT NULL]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020/03/18 10:50:59 cmd.Run() failed with exit status 1
ola@Olas-personal-MBP simple % 
```

need to handle this because this will be something that for sure happens in real life.  now it's all test data so can easily just delete table and start over. 

need to provide a way for user to provide default or ask them to change it to nullable.

**Comment by lolopinto** [comment]
closed in https://github.com/lolopinto/ent/pull/410
