### ISSUE TITLE
index on non-obvious UUID field issue

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#626]
```
    UUIDType({
      name: 'context_id',
      polymorphic: true,
      nullable: true,
      index: true,
    }),
``` 

leads to an error in codegen because the query isn't generated

```diff
import {ContextIdToFormResponsesQuery, NodeType} from "../internal";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:692:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:696:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:883:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:1185:30)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1309:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: `\x1B[96msrc/ent/generated/form_response_base.ts\x1B[0m:\x1B[93m8\x1B[0m:\x1B[93m9\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2305: \x1B[0mModule '"../internal"' has no exported member 'ContextIdToFormResponsesQuery'.\n` +
    '\n' +
    '\x1B[7m8\x1B[0m import {ContextIdToFormResponsesQuery, NodeType} from "../internal";\n' +
    '\x1B[7m \x1B[0m \x1B[91m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2305 ]
}
Error: error writing schema file: exit status 1

```

**Comment by lolopinto** [comment]
probably related to https://github.com/lolopinto/ent/issues/476

**Comment by lolopinto** [comment]
hmm. https://github.com/lolopinto/ent/blob/main/examples/simple/src/schema/comment.ts#L16 generates https://github.com/lolopinto/ent/blob/main/examples/simple/src/ent/generated/comment_query_base.ts#L71-L91 so it's probably just logic relating to if the file(s) should be generated in the first place.

**Comment by lolopinto** [comment]
fixed
